Repository fabric8io/docker-maven-plugin, pull requests merged in 2019-04, with the labels that each got.

#1179 Added 'autoRemove' option
  src/main/asciidoc/inc/start/_configuration.adoc
  src/main/java/io/fabric8/maven/docker/access/ContainerHostConfig.java
  src/main/java/io/fabric8/maven/docker/config/RunImageConfiguration.java
  src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
  src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
  src/main/java/io/fabric8/maven/docker/service/RunService.java
  src/test/java/io/fabric8/maven/docker/access/ContainerHostConfigTest.java
  src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
  src/test/java/io/fabric8/maven/docker/service/RunServiceTest.java
  src/test/resources/docker/containerCreateConfigAll.json
  src/test/resources/docker/containerHostConfigAll.json
Labels: update changelog

#1057 Add support of docker multi stage builds
  src/main/java/io/fabric8/maven/docker/service/BuildService.java
  src/main/java/io/fabric8/maven/docker/util/DockerFileUtil.java
  src/test/java/io/fabric8/maven/docker/service/BuildServiceTest.java
  src/test/java/io/fabric8/maven/docker/util/DockerFileUtilTest.java
  src/test/resources/io/fabric8/maven/docker/util/Dockerfile_multi_stage
Labels: waiting on feedback

#1189 Added 'contextDir' configuration option. Used to specify Docker build context
  doc/changelog.md
  samples/dockerfile/pom.xml
  src/main/asciidoc/inc/build/_overview.adoc
  src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java
  src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java
  src/main/java/io/fabric8/maven/docker/config/ConfigHelper.java
  src/main/java/io/fabric8/maven/docker/config/handler/property/ConfigKey.java
  src/main/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandler.java
  src/test/java/io/fabric8/maven/docker/config/BuildImageConfigurationTest.java
  src/test/java/io/fabric8/maven/docker/config/handler/property/PropertyConfigHandlerTest.java
Labels: changes requested

#1192 Change docker.verbose parameter to String to handle multiple logging levels
  doc/changelog.md
  src/main/asciidoc/inc/_global-configuration.adoc
  src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java
  src/main/java/io/fabric8/maven/docker/BuildMojo.java
  src/main/java/io/fabric8/maven/docker/access/chunked/BuildJsonResponseHandler.java
  src/main/java/io/fabric8/maven/docker/access/hc/DockerAccessWithHcClient.java
  src/main/java/io/fabric8/maven/docker/access/util/EnvCommand.java
  src/main/java/io/fabric8/maven/docker/access/util/ExternalCommand.java
  src/main/java/io/fabric8/maven/docker/config/handler/ImageConfigResolver.java
  src/main/java/io/fabric8/maven/docker/util/AnsiLogger.java
  src/main/java/io/fabric8/maven/docker/util/CredentialHelperClient.java
  src/main/java/io/fabric8/maven/docker/util/Logger.java
  src/test/java/integration/DockerAccessIT.java
  src/test/java/integration/DockerAccessWinIT.java
  src/test/java/integration/DockerMachineIT.java
  src/test/java/io/fabric8/maven/docker/assembly/DockerAssemblyManagerTest.java
  src/test/java/io/fabric8/maven/docker/assembly/MappingTrackArchiverTest.java
  src/test/java/io/fabric8/maven/docker/config/ConfigHelperTest.java
  src/test/java/io/fabric8/maven/docker/util/AnsiLoggerTest.java
Labels: waiting on feedback
